name             'stackstudio'
maintainer       'Transcend Computing'
maintainer_email 'cstewart@momentumsi.com'
license          'Apache 2.0'
description      'Installs/Configures stackstudio'
long_description 'Installs/Configures stackstudio'
version          '0.1.1'

depends 'apt'
depends 'logrotate'
depends 'nodejs', '1.3.0'
depends 'nginx', '2.7.4'
